version: "3.3"
services:
  server:
    build:
      context: ./docker/node
      args:
        - NODE_VERSION=8
        - PROJECT_PATH=/opt/app/
        - NODE_ENV=development
    environment:
      - env=development
      - PORT=4000
      - DOMAIN_WHITE_LIST=http://localhost:3000 http://localhost
    volumes:
      - ./server:/opt/app
    ports:
      - "4000:4000"
    entrypoint: entrypoint "npm run start"
    tty: true

  client:
    build:
      context: ./docker/node
      args:
        - NODE_VERSION=12
        - PROJECT_PATH=/opt/app/
        - NODE_ENV=development
    environment:
      - env=development
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./client:/opt/app
    ports:
      - "3000:3000"
    entrypoint: entrypoint "npm run start"
    tty: true
